AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: An Amazon S3 trigger that retrieves metadata for the object that has been updated.
Parameters:
  BucketNameParameter:
    Type: String
Resources:
  s3getobject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: An Amazon S3 trigger that retrieves metadata for the object that has been updated.
      MemorySize: 128
      Timeout: 3
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketNameParameter
      Events:
        objectStore8D65849F:
          Type: S3
          Properties:
            Bucket: !Ref objectStore8D65849F
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*
  objectStore8D65849F:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-objectstore8d65849f